name: gapura
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  fl_chart: ^0.36.1
  provider: ^5.0.0
  data_table_2: ^2.0.3
  fluttertoast: ^8.0.9
  http: ^0.13.4
  html_editor_enhanced: ^2.4.0+1
  hexcolor: ^2.0.7
  image_picker: ^0.8.5+3
  cross_file_image: ^0.0.2
  flutter_dotenv: ^5.0.2
  http_parser: ^4.0.1
  file_picker: ^4.5.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env